# kind-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: mud
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry.johannsen.cloud:5000"]
      endpoint = ["http://registry.johannsen.cloud:5000"]
    [plugins."io.containerd.grpc.v1.cri".registry.configs."registry.johannsen.cloud:5000".tls]
      insecure_skip_verify = true
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30400
        hostPort: 4000
        protocol: TCP
