apiVersion: v1
kind: Service
metadata:
  name: gameserver
  namespace: mud
spec:
  type: LoadBalancer
  selector:
    app: gameserver
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
