{{- if not .Values.postgres.hostPath }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: mud
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.postgres.storageClass }}
  storageClassName: {{ .Values.postgres.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}
{{- end }}
