# deployments/k8s/mud/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mud-credentials
  namespace: mud
type: Opaque
stringData:
  db-user: {{ required "db.user is required" .Values.db.user | quote }}
  db-password: {{ required "db.password is required" .Values.db.password | quote }}
  db-name: {{ required "db.name is required" .Values.db.name | quote }}
